background_opacity          0.6
cursor_trail                1
window_padding_width        25

# macOS & Universal Copy / Paste shortcuts
map super+c copy_to_clipboard
map super+v paste_from_clipboard
map cmd+c   copy_to_clipboard
map cmd+v   paste_from_clipboard
map ctrl+v  paste_from_clipboard

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

font_family MesloLGMDZ Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
