mode = "dark"

accent = "#95cdf7"
selection = "#313539"
muted = "#8b9198"

background = "#101417"
dark_background = "#181c20"
darker_background = "#0b0f12"
lighter_background = "#262a2e"

foreground = "#e0e3e8"
dark_foreground = "#8b9198"
light_foreground = "#c1c7ce"
bright_foreground = "#e0e3e8"

red = "#ffb4ab"
green = "#95cdf7"
yellow = "#b7c9d9"
blue = "#95cdf7"
magenta = "#cec0e8"
cyan = "#b7c9d9"
orange = "#4c4163"
brown = "#41474d"

bright_red = "#ffb4ab"
bright_green = "#95cdf7"
bright_yellow = "#b7c9d9"
bright_blue = "#95cdf7"
bright_magenta = "#cec0e8"
bright_cyan = "#b7c9d9"

