[colors.primary]
background = '#121318'
foreground = '#e3e1e9'

[colors.cursor]
text = '#121318'
cursor = '#e3e1e9'

[colors.vi_mode_cursor]
text = '#121318'
cursor = '#b9c3ff'

[colors.search.matches]
foreground = '#46464f'
background = '#e5bad8'

[colors.search.focused_match]
foreground = '#46464f'
background = '#b9c3ff'

[colors.footer_bar]
foreground = '#46464f'
background = '#e3e1e9'

[colors.hints.start]
foreground = '#46464f'
background = '#c3c5dd'

[colors.hints.end]
foreground = '#46464f'
background = '#c3c5dd'

[colors.selection]
text = '#c6c5d0'
background = '#46464f'


[colors.normal]
black   = '#46464f'
red     = '#ffb4ab'
green   = '#b9c3ff'
yellow  = '#c3c5dd'
blue    = '#e5bad8'
magenta = '#b9c3ff'
cyan    = '#c3c5dd'
white   = '#e3e1e9'


[colors.bright]
black   = '#90909a'
red     = '#ffb4ab'
green   = '#b9c3ff'
yellow  = '#c3c5dd'
blue    = '#e5bad8'
magenta = '#b9c3ff'
cyan    = '#c3c5dd'
white   = '#e3e1e9'


[colors.dim]
black   = '#46464f'
red     = '#ffb4ab'
green   = '#b9c3ff'
yellow  = '#c3c5dd'
blue    = '#e5bad8'
magenta = '#b9c3ff'
cyan    = '#c3c5dd'
white   = '#e3e1e9'
